#ifndef __EXIT_CODE_H__
#define __EXIT_CODE_H__

typedef enum
{
    UNKNOWN_ERROR_EXIT = 1000,
    CORE_STATE_CONFLICT_EXIT,
    SIGNALLING_SERVER_REGISTRATION_ERROR_EXIT,
    SIGNALLING_SERVER_CONNECTION_ERROR_EXIT,
    PIPELINE_ERROR_EXIT,
    DATA_CHANNEL_ERROR_EXIT,
    SESSION_DENIED_EXIT,
    
    CORRUPTED_CONFIG_FILE_EXIT,
    PLUGINS_MISSING_EXIT,

    FORCE_EXIT,
    UNKNOWN_PACKAGE_FROM_CLIENT
}ExitCode;

#endif